apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
        - name: devops-app
          image: douaabousnitra/devops-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20   # wait longer for Flask to start
            periodSeconds: 5          # check every 5 seconds
            failureThreshold: 6       # allow 6 failures before marking pod as Unready
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30   # start checking after app starts
            periodSeconds: 10         # check every 10s
            failureThreshold: 3       # restart container if failing 3 times
